In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import re

In [2]:
documents = [
    "This is a list which containig sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings."
]

In [3]:
query="what is keyword-based search?"

In [5]:
# preprocess the documents
def preprocessing_text(text: str):
    processed_text = text.lower()
    # remove punctuation
    processed_text = re.sub(r'[^\w\s]', '', processed_text)
    return processed_text

In [6]:
processed_documents = [preprocessing_text(doc) for doc in documents]
processed_documents

['this is a list which containig sample documents',
 'keywords are important for keywordbased search',
 'document analysis involves extracting keywords',
 'keywordbased search relies on sparse embeddings']

In [8]:
processed_query = preprocessing_text(query)
processed_query

'what is keywordbased search'

In [9]:
# declare vectorizor
vectorizer = TfidfVectorizer()

In [18]:
X = vectorizer.fit_transform(processed_documents)

In [19]:
X.toarray()

array([[0.        , 0.        , 0.37796447, 0.        , 0.37796447,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.37796447, 0.        , 0.        , 0.37796447, 0.        ,
        0.        , 0.37796447, 0.        , 0.        , 0.37796447,
        0.37796447],
       [0.        , 0.4533864 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4533864 , 0.4533864 , 0.        ,
        0.        , 0.35745504, 0.35745504, 0.        , 0.        ,
        0.        , 0.        , 0.35745504, 0.        , 0.        ,
        0.        ],
       [0.46516193, 0.        , 0.        , 0.46516193, 0.        ,
        0.        , 0.46516193, 0.        , 0.        , 0.46516193,
        0.        , 0.        , 0.36673901, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.43671931, 0.        , 0.        , 0.       

In [20]:
y = vectorizer.transform([processed_query])
y.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.66767854, 0.52640543, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.52640543, 0.        , 0.        ,
        0.        ]])

In [21]:
similarities = cosine_similarity(X, y)
similarities

array([[0.25235877],
       [0.37633255],
       [0.        ],
       [0.36249807]])

In [26]:
ranked_indices=np.argsort(similarities,axis=0)[::-1].flatten()
ranked_indices

array([1, 3, 0, 2])

In [28]:
ranked_documents = [documents[i] for i in ranked_indices]
ranked_documents

['Keywords are important for keyword-based search.',
 'Keyword-based search relies on sparse embeddings.',
 'This is a list which containig sample documents.',
 'Document analysis involves extracting keywords.']

In [29]:
# Output the ranked documents
for i, doc in enumerate(ranked_documents):
    print(f"Rank {i+1}: {doc}")

Rank 1: Keywords are important for keyword-based search.
Rank 2: Keyword-based search relies on sparse embeddings.
Rank 3: This is a list which containig sample documents.
Rank 4: Document analysis involves extracting keywords.


In [32]:
!pip install sentence_transformers
!pip install ipywidgets

In [33]:
# semantic search
from sentence_transformers import SentenceTransformer

In [34]:
model = SentenceTransformer('all-MiniLM-L6-v2')

In [35]:
model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [36]:
# generate Embedding for both documents and query
documents_embedding = model.encode(processed_documents)
documents_embedding

array([[-0.03365192,  0.05895169, -0.01905189, ...,  0.0916969 ,
         0.05896   ,  0.04358854],
       [-0.01219701, -0.03611696,  0.00279135, ..., -0.01717375,
        -0.0070878 ,  0.05394758],
       [-0.04765302,  0.07281729, -0.01005207, ...,  0.03264488,
         0.05722312,  0.01639589],
       [-0.02350728, -0.08621618,  0.05095091, ..., -0.05444161,
        -0.00179325,  0.06482843]], shape=(4, 384), dtype=float32)

In [37]:
query_embedding = model.encode([processed_query])

In [38]:
similarities2 = cosine_similarity(query_embedding, documents_embedding)[0]
similarities2

array([0.22491246, 0.8603974 , 0.50193006, 0.7441424 ], dtype=float32)

In [39]:
ranked_indices2 = np.argsort(similarities2)[::-1]

In [40]:
ranked_indices2

array([1, 3, 2, 0])

In [41]:
ranked_documents2 = [documents[i] for i in ranked_indices2]
ranked_documents2

['Keywords are important for keyword-based search.',
 'Keyword-based search relies on sparse embeddings.',
 'Document analysis involves extracting keywords.',
 'This is a list which containig sample documents.']

In [42]:
for i, doc in enumerate(ranked_documents):
    print(f"Rank {i+1}: {doc}")

Rank 1: Keywords are important for keyword-based search.
Rank 2: Keyword-based search relies on sparse embeddings.
Rank 3: This is a list which containig sample documents.
Rank 4: Document analysis involves extracting keywords.


In [43]:
ranked_documents

['Keywords are important for keyword-based search.',
 'Keyword-based search relies on sparse embeddings.',
 'This is a list which containig sample documents.',
 'Document analysis involves extracting keywords.']